- name: Install yum-utils, nano, curl, nmap, tcpdump, strace
  ansible.builtin.yum:
    name:
      - yum-utils
      - nano
      - curl
      - nmap
      - tcpdump
      - strace
      - mc
      - python3-pip
    state: present
