---
- name: Install python modules for managing kubernetes using kubectl
  ansible.builtin.pip:
    name:
      - packaging
      - pyyaml
      - kubernetes
      - jsonpatch

# tasks file for k8s_core_deployments
- name: Apply tigera-operator manifest
  kubernetes.core.k8s:
    definition: "{{ lookup('url', tigera_operator_url, split_lines=False) }}"
    state: present
    apply: yes
    server_side_apply:
      field_manager: ansible
    kubeconfig: /etc/kubernetes/admin.conf

- name: Download calico custom resources
  ansible.builtin.get_url:
    url: "{{ calico_custom_resources_url }}"
    dest: /tmp/custom_resources.yml
    mode: '0440'

- name: Replace pod CIDR inside calico resources file
  ansible.builtin.replace:
    path: /tmp/custom_resources.yml
    regexp: 'cidr\: 192\.168\.0\.0\/16$'
    replace: 'cidr: {{ pod_network_cidr }}'

- name: Apply calico custom_resources.yml manifest
  kubernetes.core.k8s:
    src: /tmp/custom_resources.yml
    state: present
    apply: yes
    kubeconfig: /etc/kubernetes/admin.conf

# ---
- name: Delete Calico
  k8s:
    definition: "{{ lookup('url', tigera_operator_url, split_lines=False) }}"
    state: absent
  ignore_errors: yes
  when:
    - inventory_hostname == "node1"
  tags: [never, delete_calico]

- name: Remove Calico configuration for NetworkManager
  file:
    path: "{{ k8s_calico_netmgr_path }}/conf.d/calico.conf"
    state: absent
  when:
    - _netmgr.stat.isdir is defined and _netmgr.stat.isdir
  tags: [never, delete_calico]

- name: Collect host ip links
  shell: >
    ip -json link
  register: _host_links
  tags: [never, delete_calico]

- name: Delete remanent Calico links
  shell: |
    ifconfig down "{{ item.ifname }}"
    ip link delete "{{ item.ifname }}"
  when:
    - item.ifname is match("^(br\-|cali)([0-9a-z])+")
  with_items: "{{ _host_links.stdout | from_json }}"
  tags: [never, delete_calico]

- name: Delete remanent Calico configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/cni/net.d/10-calico.conflist"
    - "/etc/cni/net.d/calico-kubeconfig"
    - "/var/lib/cni"
  tags: [never, delete_calico]

#---
- name: Apply metrics server manifest
  kubernetes.core.k8s:
    definition: "{{ lookup('url', metrics_server_url, split_lines=False) }}"
    state: present
    apply: yes
    server_side_apply:
      field_manager: ansible
    kubeconfig: /etc/kubernetes/admin.conf

#---
- name: Install Helm
  become: yes
  tasks:
    - name: Download Helm installation script
      ansible.builtin.get_url:
        url: "{{ helm_install_script_url }}"
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installation script
      ansible.builtin.command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      register: helm_install_result
      changed_when: false

    - name: Add /usr/local/bin to PATH
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/bin'
      when: helm_install_result.rc == 0

    - name: Delete helm temp installation file
      ansible.builtin.file:
        path: /tmp/kubeadm_init_config.yml
        state: absent

#---
- name: Install Kubernetes Dashboard
  become: yes
  tasks:
    - name: Add Dashboard repository
      kubernetes.core.helm_repository:
        name: stable
        repo_url: "https://kubernetes.github.io/ingress-nginx"
